### ISSUE TITLE
Standardize output

### ISSUE THREAD

**Issue by leonlan** [leonlan/CVRPLIB#20]
To support more instances, it's best to standardize the output to a dictionary. Currently I have added extra attributes etc. which I might want to remove as well later.

## TODOs
- [x] Reorganizes code base
- [x] Standardizes output to dictionary / removes Instance class.
- [x] Removes DEPOT constant
