### ISSUE TITLE
Redesign test suite

### ISSUE THREAD

**Issue by leonlan** [leonlan/CVRPLIB#37]
I have been sloppy in writing my tests. Especially with the module rehaul, most of the tests are not in the right place, or not even implemented at all. I think that `coverage` can be very helpful to detect the missing spots.

### TODOs
- [x] Add `coverage`
- [x] Implement tests for `parse` module
- [ ] Gather all the VRPLIB instances that you can find
   - [ ] ORTEC Euro-NeurIPS VRPTW instances
